# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
txt="welcome to the jungle"
x=txt.split()
print(x)

['welcome', 'to', 'the', 'jungle']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [2]:
# using format option for a
# value stored in a variable
str = "This article is written in {}"
print(str.format("Python"))
 
# formatting a string using a numeric constant
print("Hello, I am {} years old !".format(18))

This article is written in Python
Hello, I am 18 years old !


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
{
  "stairs_1":[
    1,
    "two",
    {
      "stairs_2":[
        "Close to the door",
        {
          "in the door":[
            "one",
            2,
            [
              "hello"
            ]
          ]
        }
      ]
    }
  ]
}

{'stairs_1': [1,
  'two',
  {'stairs_2': ['Close to the door', {'in the door': ['one', 2, ['hello']]}]}]}

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [15]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [13]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print (array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [9]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
 
 
b = np.array([4, 5, 6])
print(b)
 
print('\n---Result of a and b---')
print(np.concatenate((a, b)))

[1 2 3]
[4 5 6]

---Result of a and b---
[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [12]:
import pandas as pd
# Calling DataFrame constructor
df = pd.DataFrame()
 
print(df)

Empty DataFrame
Columns: []
Index: []


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [11]:
import datetime

import pandas as pd
 
# initializing date

test_date = datetime.datetime.strptime("01-7-2022", "%d-%m-%Y")
 
# initializing K 

K = 5
 

date_generated = pd.date_range(test_date, periods=K)

print(date_generated.strftime("%d-%m-%Y"))

Index(['01-07-2022', '02-07-2022', '03-07-2022', '04-07-2022', '05-07-2022'], dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [10]:
import pandas as pd   

      
# List1   

lst = [['Geek', 25], ['is', 30],  

       ['for', 26], ['Geeksforgeeks', 22]]  

  
# creating df object with columns specified     

df = pd.DataFrame(lst, columns =['Tag', 'number'])  

print(df )

             Tag  number
0           Geek      25
1             is      30
2            for      26
3  Geeksforgeeks      22
